name: jwhobuzzweb
dependencies:
  polymer: ">=0.13.0 <0.14.0"
  core_elements: ">=0.2.0 <0.3.0"
  paper_elements: ">=0.1.0 <0.2.0"

  browser: any

transformers:
- polymer:
    entry_points: web/jwhobuzzweb/index.html